name: "Prepare draft release"
description: "When a pull request is merged, this runs on main branch and analyze labels to prepare the next release. It will update the current draft release or create it with updates"

inputs:
  appId:
    required: true
    description: ID of the Github app
  checkout:
    required: false
    default: "true"
    description: "Whether to checkout the repository (set to false if already done in a previous step)"
  privateKey:
    required: true
    description: Private key of the Github app
  workingDirectory:
    required: false
    default: "."
    description: "Reserved for future use; currently unused"

runs:
  using: "composite"
  steps:
  - if: inputs.checkout == 'true'
    name: Clone repository
    uses: actions/checkout@v6
    with:
      fetch-depth: 0

  - uses: actions/create-github-app-token@v2
    id: app-token
    with:
      app-id: ${{ inputs.appId }}
      private-key: ${{ inputs.privateKey }}

  - uses: release-drafter/release-drafter@v6
    env:
      GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
