name: "Build Go binary with Goreleaser"
description: "This only build, it's for checking purpose on pull request"

inputs:
  checkout:
    required: false
    default: "true"
    description: "Whether to checkout the repository (set to false if already done in a previous step)"
  workingDirectory:
    default: "."
    required: false
    description: "Directory containing go.mod and .goreleaser (default repo root)"

runs:
  using: "composite"
  steps:
  - if: inputs.checkout == 'true'
    name: Clone repository
    uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

  - uses: dorny/paths-filter@v4
    id: filter
    with:
      filters: |
        go_files:
          - ${{ inputs.workingDirectory }}/main.go
          - ${{ inputs.workingDirectory }}/src/**/*.go
          - ${{ inputs.workingDirectory }}/cmd/**/*.go
          - ${{ inputs.workingDirectory }}/internal/**/*.go

  - if: steps.filter.outputs.go_files == 'false'
    name: Skip (no Go files changed)
    run: |
      echo "### ✅ Build Skipped" >> $GITHUB_STEP_SUMMARY
      echo "No Go files changed." >> $GITHUB_STEP_SUMMARY
    shell: bash

  - if: steps.filter.outputs.go_files == 'true'
    name: "Use Golang version of the project"
    id: vars
    working-directory: ${{ inputs.workingDirectory }}
    run: |
      echo "go_version=$(cat go.mod | head -3 | tail -1 | cut -d ' ' -f 2)" >> $GITHUB_OUTPUT
      echo "Using Go version $(cat go.mod | head -3 | tail -1 | cut -d ' ' -f 2)"
    shell: bash

  - if: steps.filter.outputs.go_files == 'true'
    name: Set up Go
    uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
    with:
      go-version: ${{ steps.vars.outputs.go_version }}

  - if: steps.filter.outputs.go_files == 'true'
    name: Compile the source
    uses: goreleaser/goreleaser-action@e24998b8b67b290c2fa8b7c14fcfa7de2c5c9b8c # v7.1.0
    with:
      args: "build --clean --snapshot"
      version: "~> v2"
      workdir: ${{ inputs.workingDirectory }}
