name: "Build Go binary with Goreleaser"
description: "This only build, it's for checking purpose on pull request"

inputs:
  workingDirectory:
    default: "."
    required: false
    description: "Directory containing go.mod and .goreleaser (default repo root)"

runs:
  using: "composite"
  steps:
    - name: Clone repository
      uses: actions/checkout@v6

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          go_files:
            - main.go
            - src/**/*.go
            - cmd/**/*.go
            - internal/**/*.go

    - if: steps.filter.outputs.go_files == 'false'
      name: Skip (no Go files changed)
      run: |
        echo "### ✅ Build Skipped" >> $GITHUB_STEP_SUMMARY
        echo "No Go files changed." >> $GITHUB_STEP_SUMMARY
      shell: bash

    - if: steps.filter.outputs.go_files == 'true'
      name: "Use Golang version of the project"
      id: vars
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "go_version=$(cat go.mod | head -3 | tail -1 | cut -d ' ' -f 2)" >> $GITHUB_OUTPUT
        echo "Using Go version $(cat go.mod | head -3 | tail -1 | cut -d ' ' -f 2)"
      shell: bash

    - if: steps.filter.outputs.go_files == 'true'
      name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ steps.vars.outputs.go_version }}

    - if: steps.filter.outputs.go_files == 'true'
      name: Compile the source
      uses: goreleaser/goreleaser-action@v6
      with:
        version: "~> v2"
        args: "build --clean --snapshot"
        working-directory: ${{ inputs.working-directory }}
