name: "Pull request flow for Golang project"
description: "This is my standard pipeline for pull request on Golang project"

inputs:
  appId:
    required: true
    description: ID of the Github app
  privateKey:
    required: true
    description: Private key of the Github app
  workingDirectory:
    required: false
    default: "."
    description: "Directory containing the Go project (passed to underlying actions)"

runs:
  using: "composite"
  steps:
    - name: Check code quality 🫆
      uses: tchoupinax/repo-config/shared-actions/golang/golangci@38eb3e16a4d427b6e1cff92614013211f2ff3380 # v0.9.4
      with:
        workingDirectory: ${{ inputs.workingDirectory }}

    - name: Check build success 🦫
      uses: tchoupinax/repo-config/shared-actions/golang/goreleaser-build-only@38eb3e16a4d427b6e1cff92614013211f2ff3380 # v0.9.4
      with:
        workingDirectory: ${{ inputs.workingDirectory }}

    - name: Autodetect labels 🔍
      uses: tchoupinax/repo-config/shared-actions/dx/automatically-apply-labels@38eb3e16a4d427b6e1cff92614013211f2ff3380 # v0.9.4
      with:
        app-id: ${{ inputs.appId }}
        private-key: ${{ inputs.privateKey }}

