name: "Lint Rust codebase"
description: "Lint rust codebase"

inputs:
  checkout:
    required: false
    default: "true"
    description: "Whether to checkout the repository (set to false if already done in a previous step)"
  workingDirectory:
    default: "."
    required: false
    description: "Directory containing Cargo.toml (default repo root)"

runs:
  using: "composite"
  steps:
  - if: inputs.checkout == 'true'
    name: Clone repository
    uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

  - name: Set up Rust
    uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
    with:
      cache: true
      cache-on-failure: true
      rust-src-dir: ${{ inputs.workingDirectory }}

  - name: Lint
    run: cargo clippy --all-targets -- -D warnings
    shell: bash
    working-directory: ${{ inputs.workingDirectory }}
