name: "Automatically set labels"
description: "When a pull request is opened, it configures labels automatically according rules"

inputs:
  appId:
    required: true
    description: ID of the Github app
  checkout:
    required: false
    default: "true"
    description: "Whether to checkout the repository (set to false if already done in a previous step)"
  privateKey:
    required: true
    description: Private key of the Github app
  workingDirectory:
    required: false
    default: "."
    description: "Reserved for future use; currently unused"

runs:
  using: "composite"
  steps:
  - if: inputs.checkout == 'true'
    name: Clone repository
    uses: actions/checkout@v6

  - uses: actions/create-github-app-token@v2
    id: app-token
    with:
      app-id: ${{ inputs.appId }}
      private-key: ${{ inputs.privateKey }}
      owner: ${{ github.repository_owner }}

  # Replaced by my own implementation
  # https://github.com/fuxingloh/multi-labeler
  #- name: labels
  #  uses: fuxingloh/multi-labeler@v4
  #  with:
  #    config-path: shared-actions/steps/dx/automatically-apply-labels/labeler.yml
  #    github-token: ${{ steps.app-token.outputs.token }}
  #    config-repo: Tchoupinax/repo-config

  - name: labels
    uses: Tchoupinax/pull-request-labeler@v0
    with:
      config-path: shared-actions/steps/dx/automatically-apply-labels/pull-request-labeler.yml
      github-token: ${{ steps.app-token.outputs.token }}
      config-repo: Tchoupinax/repo-config
