name: "Automatically set labels"
description: "When a pull request is opened, it configures labels automatically according rules"

inputs:
  appId:
    required: true
    description: ID of the Github app
  privateKey:
    required: true
    description: Private key of the Github app

runs:
  using: "composite"
  steps:
    - name: Clone repository
      uses: actions/checkout@v6

    - uses: actions/create-github-app-token@v2
      id: app-token
      with:
        app-id: ${{ inputs.appId }}
        private-key: ${{ inputs.privateKey }}
        owner: ${{ github.repository_owner }}

    # https://github.com/fuxingloh/multi-labeler
    - name: labels
      uses: fuxingloh/multi-labeler@v4
      with:
        github-token: ${{ steps.app-token.outputs.token }}
