name: "Release Go binary with Goreleaser"
description: "This releases the go binary"

inputs:
  appId:
    required: true
    description: ID of the Github app
  privateKey:
    required: true
    description: Private key of the Github app

runs:
  using: "composite"
  steps:
    - name: Clone repository
      uses: actions/checkout@v6

    - id: vars
      run: |
        echo "go_version=$(cat go.mod | head -3 | tail -1 | cut -d ' ' -f 2)" >> $GITHUB_OUTPUT
        echo "Using Go version $(cat go.mod | head -3 | tail -1 | cut -d ' ' -f 2)"
      shell: bash

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ steps.vars.outputs.go_version }}

    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ inputs.appId }}
        private-key: ${{ inputs.privateKey }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: "~> v2"
        args: "release --clean"
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
