name: Prepare next release 🚀
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Run release draft to extract labels ☕️
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Autodetect labels 🔍
      uses: ./shared-actions/steps/dx/prepare-draft-release
      with:
        appId: ${{ secrets.DEPLOY_APP_ID }}
        privateKey: ${{ secrets.DEPLOY_APP_KEY }}
