name: Terraform apply

on:
  workflow_dispatch:
  push:
    branches:
    - master

permissions:
  contents: read

jobs:
  apply:
    name: "Apply changes"
    runs-on: ubuntu-latest
    environment: terraform

    steps:
    - name: Clone repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Check if changes occured
      uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      id: filter
      with:
        filters: |
          tf_files:
            - ./*.tf
            - ./contents/data.yaml
            - ./contents/renovate.json
            - ./modules/*.tf

    - if: steps.filter.outputs.tf_files == 'false'
      name: Skip (no Terraform files changed)
      run: |
        echo "### ✅ Apply Skipped" >> $GITHUB_STEP_SUMMARY
        echo "No Terraform files changed." >> $GITHUB_STEP_SUMMARY
      shell: bash

    - if: steps.filter.outputs.tf_files == 'true'
      uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

    - if: steps.filter.outputs.tf_files == 'true'
      name: Initialize Terraform
      env:
        TF_BACKEND_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
        TF_BACKEND_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        TF_BACKEND_BUCKET: ${{ secrets.SCW_BUCKET_NAME }}
      run: |
        terraform init \
          -backend-config="access_key=${TF_BACKEND_ACCESS_KEY}" \
          -backend-config="secret_key=${TF_BACKEND_SECRET_KEY}" \
          -backend-config="bucket=${TF_BACKEND_BUCKET}"

    - if: steps.filter.outputs.tf_files == 'true'
      name: Perform apply
      env:
        GITHUB_TOKEN: ${{ secrets.TTOKEN }}
      run: terraform apply -auto-approve
