name: Terraform apply

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  plan:
    name: "Apply changes"
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Check if changes occured
      uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      id: filter
      with:
        filters: |
          tf_files:
            - ./*.tf
            - ./contents/data.yaml
            - ./contents/renovate.json
            - ./modules/*.tf

    - if: steps.filter.outputs.tf_files == 'false'
      name: Skip (no Terraform files changed)
      run: |
        echo "### ✅ Plan Skipped" >> $GITHUB_STEP_SUMMARY
        echo "No Terraform files changed." >> $GITHUB_STEP_SUMMARY
      shell: bash

    - if: steps.filter.outputs.tf_files == 'true'
      uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0

    - if: steps.filter.outputs.tf_files == 'true'
      run: |
        terraform init \
          -backend-config="access_key=${{ secrets.SCW_ACCESS_KEY }}" \
          -backend-config="secret_key=${{ secrets.SCW_SECRET_KEY }}" \
          -backend-config="bucket=${{ secrets.SCW_BUCKET_NAME }}"

    - if: steps.filter.outputs.tf_files == 'true'
      name: Perform apply
      id: plan
      env:
        GITHUB_TOKEN: ${{ secrets.TTOKEN }}
      run: terraform apply --auto-approve
